export const BOTS = [
  {
    id: 'music',
    name: 'Dominyx Music',
    short: 'Music',
    emoji: '🎵',
    tagline: 'Nonstop music for your VC',
    description: 'Keep the party going — queue songs, loop, shuffle, and control it all from buttons.',
    features: ['24/7 mode', 'Queue & playlists', 'Loop & shuffle', 'Now-playing controls'],
    color: '#8B5CF6',
  },
  {
    id: 'level',
    name: 'Dominyx Level',
    short: 'Levels',
    emoji: '🏆',
    tagline: 'Turn chat into a competition',
    description: 'Members earn XP, rank up, and unlock roles as they talk.',
    features: ['XP per message', 'Ranks & leaderboard', 'Level role rewards', 'Custom announcements'],
    color: '#2ECC71',
  },
  {
    id: 'greet',
    name: 'Dominyx Greet',
    short: 'Welcome',
    emoji: '👋',
    tagline: 'Welcomes that wow',
    description: 'Beautiful join cards, custom messages, and auto-roles for every newcomer.',
    features: ['Welcome cards', 'Custom messages', 'Auto-role on join'],
    color: '#DC143C',
  },
  {
    id: 'ticket',
    name: 'Dominyx Ticket',
    short: 'Support',
    emoji: '🎫',
    tagline: 'Support without chaos',
    description: 'One-click panels with categories, priorities, and full transcripts.',
    features: ['Ticket panels', 'Categories & priority', 'Staff claims', 'Transcripts'],
    color: '#F59E0B',
  },
  {
    id: 'ping',
    name: 'Dominyx Ping',
    short: 'Alerts',
    emoji: '📡',
    tagline: 'Never miss a go-live',
    description: 'Instant pings the moment your YouTubers go live.',
    features: ['Live detection', 'Custom alert channel', 'Per-server config'],
    color: '#3B82F6',
  },
  {
    id: 'guard',
    name: 'Dominyx Guard',
    short: 'Safety',
    emoji: '🛡️',
    tagline: 'Mod team in a box',
    description: 'Bans, warns, case history, and self-assign roles — all logged.',
    features: ['Case history', 'Staff notes', 'Bulk ban', 'Self-assign roles'],
    color: '#64748B',
  },
];

export const BOT_MAP = Object.fromEntries(BOTS.map((b) => [b.id, b]));