export const BOTS = [
  {
    id: 'music',
    name: 'Dominyx Music',
    short: 'Music',
    emoji: '🎵',
    tagline: 'Nonstop music for your VC',
    description: 'High-quality voice music with queues, playlists, 24/7 mode, DJ controls, live stats, XP rewards, sleep timer, artist radio and mood mixes.',
    features: ['24/7 mode', 'Queue & playlists', 'Stats & XP', 'Radio & moods'],
    color: '#8B5CF6',
  },
  {
    id: 'level',
    name: 'Dominyx Level',
    short: 'Levels',
    emoji: '🏆',
    tagline: 'Turn chat into a competition',
    description: 'Members earn XP for chatting, climb ranks, unlock role rewards and chase the server leaderboard.',
    features: ['XP per message', 'Ranks & leaderboard', 'Level role rewards', 'Custom announcements'],
    color: '#2ECC71',
  },
  {
    id: 'greet',
    name: 'Dominyx Greet',
    short: 'Welcome',
    emoji: '👋',
    tagline: 'Welcomes that wow',
    description: 'Stunning canvas welcome cards, custom join messages, goodbyes, DM welcomes and auto-roles.',
    features: ['Welcome cards', 'Goodbye posts', 'Auto-role on join', 'DM welcomes'],
    color: '#DC143C',
  },
  {
    id: 'ticket',
    name: 'Dominyx Ticket',
    short: 'Support',
    emoji: '🎫',
    tagline: 'Support without chaos',
    description: 'One-click ticket panels with categories, staff claims, priorities, auto-close and full transcripts.',
    features: ['Ticket panels', 'Categories & priority', 'Auto-close', 'Transcripts'],
    color: '#F59E0B',
  },
  {
    id: 'ping',
    name: 'Dominyx Ping',
    short: 'Alerts',
    emoji: '📡',
    tagline: 'Never miss a go-live',
    description: 'Instant YouTube live alerts with custom messages, role pings and per-server schedules.',
    features: ['Live detection', 'Custom messages', 'Role mention', 'Per-server config'],
    color: '#3B82F6',
  },
  {
    id: 'guard',
    name: 'Dominyx Guard',
    short: 'Safety',
    emoji: '🛡️',
    tagline: 'Mod team in a box',
    description: 'Bans and warns with case history, anti-raid, anti-nuke rollback, scam filters, lockdowns and self-roles.',
    features: ['Anti-raid & anti-nuke', 'Case history', 'Scam filters', 'Lockdowns & self-roles'],
    color: '#64748B',
  },
];

export const BOT_MAP = Object.fromEntries(BOTS.map((b) => [b.id, b]));